services:
  frontend:
    build: .
    container_name: frontend_P1
    command: tail -f /dev/null
    hostname: frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend

  