services:
  frontend:
    build: ./Frontend
    container_name: frontend_FE_P1
    command: ng serve --host 0.0.0.0
    hostname: frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true